GF-188: При запросе списка трасс не запрашивать пролазы
bitia-ru/gekkon-frontend pull request #189
Opened 2020-09-08 13:33 UTC by SvetlanaBatova

В итоге отказались от идеи сохранять пролазы в локальный state, так как пролазы итак сохраняются в глобальный при запросе отдельных трасс, а обращение к пролазам происходит в нескольких компонентах, использование для хранения пролазов глобального состояния удобнее

2020-09-12 22:21 UTC, levenkov requested changes

2020-09-12 22:21 UTC, levenkov commented on src/v2/components/RouteCard/RouteCard.js
> +                  (ascentResult && ascentResult !== 'unsuccessful') && (
Выражение повторяется дважды — давай его вынесем в переменную.

2020-09-12 22:22 UTC, levenkov commented
Вроде есть какие-то отличия от исходной формулировки задачи (той, что в тикете), но не вижу описания отличий в description.

2020-09-14 19:28 UTC, SvetlanaBatova commented on src/v2/components/RouteCard/RouteCard.js
> +                  (ascentResult && ascentResult !== 'unsuccessful') && (
Вынесла

2020-09-15 10:52 UTC, levenkov approved these changes

2020-09-15 10:52 UTC, merged