GF-220: Клавиши вправо-влево на трассе мешают написанию комментария
bitia-ru/gekkon-frontend pull request #221
Opened 2020-09-24 16:04 UTC by SvetlanaBatova

2020-09-24 16:07 UTC, SvetlanaBatova commented on src/v2/components/RoutesShowModal/RoutesShowModal.js
> +    }
Более логичным кажется вариант добавить для поля с комментарием onKeyDown с event.stopPropagation(), но он не решает проблему - эвент окном все равно перехватывается и нажатие на стрелки приводит к тому, что переключаются окна трасс

2020-09-24 21:49 UTC, levenkov requested changes

2020-09-24 21:49 UTC, levenkov commented on src/v2/components/RoutesShowModal/RoutesShowModal.js
> +    }
Правильный ход мыслей был, просто не дорылась.

`event.nativeEvent.stopImmediatePropagation();`

2020-09-25 07:30 UTC, SvetlanaBatova commented on src/v2/components/RoutesShowModal/RoutesShowModal.js
> +    }
Поправила

2020-09-29 06:38 UTC, levenkov approved these changes

2020-09-29 06:38 UTC, merged