GF-224: При задании положения трассы отображать трассы на момент даты накрутки трассы
bitia-ru/gekkon-frontend pull request #225
Opened 2020-09-25 13:44 UTC by SvetlanaBatova

2020-09-28 14:43 UTC, SergBlack approved these changes

2020-09-29 07:01 UTC, levenkov approved these changes

2020-09-29 07:02 UTC, levenkov commented
1. Удалять лучше отдельным тикетом на всякий пожарный.

2020-09-29 07:04 UTC, levenkov requested changes

2020-09-29 07:04 UTC, levenkov commented on src/v2/components/SchemeModal/SchemeModal.js
> +    const currentDate = currentRoute.installed_at || DEFAULT_FILTERS.date;
Давай сделаем как ты предложила.

2020-09-29 14:42 UTC, SvetlanaBatova commented
> 1. Удалять лучше отдельным тикетом на всякий пожарный.
> 2. Тикет очень маленький, поэтому ок.
> 3. Да, ты всё правильно решила, лучше сделать именно так.

1. https://github.com/bitia-ru/gekkon-frontend/pull/238

2020-09-29 14:42 UTC, SvetlanaBatova commented on src/v2/components/SchemeModal/SchemeModal.js
> +    const currentDate = currentRoute.installed_at || DEFAULT_FILTERS.date;
Поправила

2020-09-29 23:29 UTC, levenkov requested changes

2020-09-29 23:29 UTC, levenkov commented on src/v2/components/SchemeModal/SchemeModal.js
> +      currentRoute.installed_at || currentRoute.installed_until || DEFAULT_FILTERS.date
В день, который указан в installed_until, трасса уже не показывается на схеме. Т.е., если у трассы не задана дата накрутки, задана дата скрутки и мы открываем редактор положения трассы на схеме, то по логике мы должны видеть схему дня, предшествующего дню скрутки. А при таком решении вроде мы будем видеть схему такой, какой она является уже после скрутки данной трассы.

Надо проверить так: накрутитьь трасс с датой накрутки на день X и добавить несколько трасс, у которых дня накрутки нет, но есть день скрутки и он равен X. После этого открыть одну из трасс с днём скрутки и открыть редактор положения трассы на схеме. Если мы такое делаем, мы хотим менять положение трассы относительно трасс, скрученных с данной в один день, а не накрученных следом. Т.е. мы должны на схеме видеть трассы, скрученные в день X, а не накрученные в этот день.

2020-09-30 20:30 UTC, SvetlanaBatova commented on src/v2/components/SchemeModal/SchemeModal.js
> +      currentRoute.installed_at || currentRoute.installed_until || DEFAULT_FILTERS.date
Поправила

2020-10-08 20:02 UTC, levenkov approved these changes

2020-10-08 20:04 UTC, merged