WIP: GF-228: Клавиши вверх-вниз при выборе цвета
bitia-ru/gekkon-frontend pull request #229
Opened 2020-09-25 19:24 UTC by SvetlanaBatova

2020-10-08 20:09 UTC, levenkov requested changes

2020-10-08 20:09 UTC, levenkov commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +      if (event.key === 'ArrowUp') {
Эти два блока if имеют слишком много общего. Их можно объединить.

2020-10-08 20:09 UTC, levenkov commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +    scrollToCurrentSelectedItem = () => {
В постановке задачи про скролл ничего не сказано. Опиши различия между постановкой задачи и решением в description реквеста, пожалуйста.

2020-10-20 12:06 UTC, SvetlanaBatova commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +      if (event.key === 'ArrowUp') {
Объединила

2020-10-20 12:24 UTC, SvetlanaBatova commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +                    !droppedDown && styles.comboBoxDropdownHidden,
Для того, чтобы можно было сделать скролл к пункту из списка, нужны ref-ы этих пунктов, но ref-ы появляются только когда компонент рендерится, поэтому сделать droppedDown && ( рендер списка ) не получается, надо, чтобы список рендерился всегда, если его можно открыть (т.е. когда компонент editable)
Если сделать droppedDown && ( рендер списка ), то ref-ы сформируются только когда droppedDown станет true и открыть список сразу на нужном пункте не получится

2020-10-20 12:25 UTC, SvetlanaBatova commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +    scrollToCurrentSelectedItem = () => {
Описала

2020-10-20 21:29 UTC, levenkov approved these changes

2020-10-20 21:29 UTC, merged