GF-230: Селектор цвета зацепа/маркировки: добавить возможность сброса
bitia-ru/gekkon-frontend pull request #231
Opened 2020-09-28 14:05 UTC by SergBlack

Окно выбора цвета теперь имеет вид:
![RouteColorPicker](https://user-images.githubusercontent.com/45591625/94442602-d4bb9d00-01ac-11eb-8b8c-5dc3c2d7390f.png)

2020-10-02 09:58 UTC, SvetlanaBatova commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +      onSelect(null);
Лучше не менять это в коммите "Move RouteColorPicker styles into separate file"

2020-10-02 10:00 UTC, SvetlanaBatova commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +                    // style={{ outline: 'none' }}
Эта строчка в одном коммите добавляется, в другом удаляется

2020-10-02 10:03 UTC, SvetlanaBatova requested changes
Вроде все работает, и сделано логичное разбиение на смысловые коммиты, но лучше чтобы не получалось, что в одном коммите что-то добавляется, а в другом оно же убирается

2020-10-09 18:18 UTC, SergBlack commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +      onSelect(null);
Поправил коммиты

2020-10-09 18:18 UTC, SergBlack commented on src/v2/components/RouteColorPicker/RouteColorPicker.js
> +                    // style={{ outline: 'none' }}
Поправил коммиты

2020-10-09 18:19 UTC, SergBlack commented
> Вроде все работает, и сделано логичное разбиение на смысловые коммиты, но лучше чтобы не получалось, что в одном коммите что-то добавляется, а в другом оно же убирается

Идею уловил. Это логично

2020-10-19 22:36 UTC, levenkov approved these changes

2020-10-19 22:36 UTC, merged