GF-232: Автоматическое проставление категории по цвету маркировки
bitia-ru/gekkon-frontend pull request #233
Opened 2020-09-28 20:46 UTC by SergBlack

2020-10-02 10:20 UTC, SvetlanaBatova commented on src/v2/components/RoutesEditModal/RoutesEditModal.js
> +    this.setState(state => ({ route: { ...state.route, [paramName]: value } }));
Если я правильно понимаю, то при такой реализации, если например paramName === 'author', setState будет делаться два раза вместо одного, причем в промежуточном состоянии в нем будут неконсистентные данные, потому что author будет один, а author_id будет другой. В данном случае это скорее всего ничего не сломает, но мне кажется, что здесь лучше обойтись одним setState

2020-10-02 10:31 UTC, SvetlanaBatova requested changes

2020-10-02 10:31 UTC, SvetlanaBatova commented on src/v1/components/RouteDataEditableTable/RouteDataEditableTable.js
> +        onRouteParamChange(markColorToCategory[marksColor.id], 'category');
В тикете написано "если категория ещё не выбрана, то она проставляется в соответствии с этой таблицей", не очень понимаю где здесь проверяется, что категория еще не выбрана

2020-10-10 18:56 UTC, SergBlack commented on src/v2/components/RoutesEditModal/RoutesEditModal.js
> +    this.setState(state => ({ route: { ...state.route, [paramName]: value } }));
Поправил.

2020-10-10 19:01 UTC, SergBlack commented on src/v1/components/RouteDataEditableTable/RouteDataEditableTable.js
> +        onRouteParamChange(markColorToCategory[marksColor.id], 'category');
Вот это надо обсудить. Получается, что при создании трассы, категория уже автоматически проставляется 5а, это то значение, что лежит в state после нажатия на кнопку Добавить трассу. Проверка тогда тут не сработает. И второй момент - с бэкэнда приходит таблица соответствия категории к цвету маркировке. Если мы начинаем проставлять по-своему, тогда непонятно вообще зачем эту фичу вводить. Категория не привязано жестко с цвету маркировки, то есть выбрать другую категорию можно.

2020-10-10 19:18 UTC, levenkov commented on src/v1/components/RouteDataEditableTable/RouteDataEditableTable.js
> +        onRouteParamChange(markColorToCategory[marksColor.id], 'category');
Да, сбросить категорию сейчас нельзя, поэтому пусть проставляется категория всегда. В любом случае категорию выбрать можно, т.ч. ок.

2020-10-19 22:46 UTC, levenkov approved these changes

2020-10-19 22:47 UTC, merged