GF-245: Брать дату пролаза при добавлении пролаза из даты в фильтрах на схеме зала
bitia-ru/gekkon-frontend pull request #246
Opened 2020-10-02 15:37 UTC by SvetlanaBatova

В тикете сейчас выполняется то, что прописано в постановке задачи, но есть несколько нелогичностей:

1) В описании тикета написано "Для не-схемы зала в случае, если трасса уже скручена, датой пролаза брать последний день активности трассы."
С одной стороны это кажется логичным, если мы открыли трассу из схемы зала и она там отображалась, то всегда можно взять дату из фильтров, потому что это значит, что на заданную дату трасса не была скручена, но на самом деле в этой логике есть одно неверное допущение.
Мы в какой-то момент разрешили открывать просмотр трассы поверх независимо от установленных фильтров, поэтому можно открыть трассу из схемы и проставить ей дату скрутки более раннюю, чем дата в фильтрах. Если в добавляемый пролаз при этом проставить дату из фильтров, то получится, что пролаз установили на дату, на которую трассу уже скрутили
2) Раньше мы всегда добавляли пролаз либо текущей датой либо последней в отсортированном списке, при той логике, которая предлагается, можно добавить пролаз на более раннюю дату, чем был последний, в итоге получается, что его надо добавлять не в конец списка, а в середину?
3) Надо видимо запретить проставлять дату пролаза больше текущей (сейчас вроде такого ограничения нет) ?

2020-10-08 13:04 UTC, levenkov commented
1. Использовать дату скрутки как ограничитель
2. Да. Меня это немного смущает, но надо посмотреть вживую
3. Да

2020-10-08 13:04 UTC, levenkov requested changes
Выполнить пункты 1-3

2020-10-20 20:39 UTC, SvetlanaBatova commented
В рамках тикета в компонент Calendar добавлена возможность передавать левое и правое ограничение для даты. Так как компонент не был переведен на aphrodite, отдельным коммитом сделан его перевод на aphrodite

2020-10-20 21:49 UTC, levenkov commented
Перепишу для себя то, что значат функции 1-3:

1. В случае проставления пролазов со схемы зала дата скрутки должна быть ограничением в том числе: т.е. в постановке задачи все верно, только надо гарантировать, что дата пролаза не за пределами даты скрутки.

2. При добавлении пролаза, если дата пролаза не больше, чем последний уже добавленный пролаз, то надо добавлять в середину таблицы пролазов (речь именно о том, как будет выглядеть эта таблица). Просто интуитивно кажется, что есть второй вариант  — добавлять всегда в конец, а если открываешь потом, то отображать уже хронологически. Но нет, пока кажется, что это не нужно.

3. Ввести ограничения на выбор даты. Т.е. добавить для DatePicker'а такую возможность.

2020-10-20 22:08 UTC, levenkov commented
Не реализован кейс из последнего абзаца постановки задачи: если надо добавить 5 пролазов не той даты, которая стоит в фильтре, придется 5 раз менять дату пролаза.

Текущий MR я принимаю, чтобы уже начать тестировать, а это упущенное надо сделать отдельным MR'ом.

2020-10-20 22:10 UTC, levenkov commented
Пункт 3 вынес в отдельный тикет: https://github.com/bitia-ru/gekkon-frontend/issues/253

@SvetlanaBatova ветку я сделал, MR только сама создай, у меня к коду в нему есть замечания.

2020-10-20 22:13 UTC, levenkov approved these changes

2020-10-20 22:13 UTC, merged