GF-267: В режиме редактирования на схеме отображать трассы на момент даты в фильтрах, если возможно
bitia-ru/gekkon-frontend pull request #270
Opened 2020-11-18 12:39 UTC by SvetlanaBatova

2020-11-18 12:54 UTC, levenkov requested changes

2020-11-18 12:54 UTC, levenkov commented on src/v2/components/SchemeModal/SchemeModal.js
> +    if (installedAt) {
Кажется, это можно сильно упросить при помощи вот этого: https://day.js.org/docs/en/plugin/is-between

2020-11-18 12:58 UTC, levenkov requested changes

2020-11-18 12:58 UTC, levenkov commented on src/v2/components/SchemeModal/SchemeModal.js
> +    this.dateFromFilters = filters.date ? dayjs(filters.date) : null;
Предлагаю завести тикет на разработку метода `parseDate`, который сможет принимать undefined и null и переделку всего в проекте на его использование.

2020-11-18 13:05 UTC, SvetlanaBatova commented on src/v2/components/SchemeModal/SchemeModal.js
> +    if (installedAt) {
Я об этом подумала, но вроде этому методу надо передавать две даты - с и по, если передать вместо одной из них null, то будет не то, что нам нужно. У нас если дата не задана, то значит нет ограничения с одной стороны, а этот метод обработает по-другому. Поэтому случаи когда дата не задана, надо обрабатывать отдельно и получится тоже самое

2020-11-18 13:06 UTC, SvetlanaBatova commented on src/v2/components/SchemeModal/SchemeModal.js
> +    this.dateFromFilters = filters.date ? dayjs(filters.date) : null;
Тогда заодно надо избавиться от moment.js

2020-11-18 13:19 UTC, levenkov commented on src/v2/components/SchemeModal/SchemeModal.js
> +    this.dateFromFilters = filters.date ? dayjs(filters.date) : null;
Обсудим это в том тикете.

2020-11-18 13:21 UTC, levenkov commented on src/v2/components/SchemeModal/SchemeModal.js
> +    if (installedAt) {
Значит надо написать свой метод, который будет работать как надо. Суть в том, что большую часть кода конструктора компонента сейчас занимает частная задача. Всегда в таких случаях эту частную задачу надо выносить.

2020-11-19 14:33 UTC, SvetlanaBatova commented on src/v2/components/SchemeModal/SchemeModal.js
> +    this.dateFromFilters = filters.date ? dayjs(filters.date) : null;
https://github.com/bitia-ru/gekkon-frontend/issues/271

2020-11-19 14:33 UTC, SvetlanaBatova commented on src/v2/components/SchemeModal/SchemeModal.js
> +    if (installedAt) {
Вынесла метод в utils

2021-02-14 13:50 UTC, levenkov approved these changes

2021-02-14 13:50 UTC, merged